CREATE TABLE Projet (id_project number(10), 
name_project varchar2(20) NOT NULL, 
status_project varchar2(30) NOT NULL, 
startDate date NOT NULL, 
endDate date NOT NULL, 
partner varchar2(30) NOT NULL, 
urlProject varchar2(25) NOT NULL, 
descriptionProject varchar2(50) NOT NULL, 
id_formation number(10) NOT NULL, 
id_exp number(10) NOT NULL, 
id_expro number(10) NOT NULL, 
PRIMARY KEY (id_projet));